### ISSUE TITLE
Dynamic Redis Docker Image

### ISSUE THREAD

**Issue by skidder** [mattsta/redis#7]
Thanks for your awesome work making the Dynamic Redis server!  Just figured I'd let you know that I created a Docker image that builds the latest unstable dynamic-redis server and krmt modules:

Dockerhub image: https://registry.hub.docker.com/u/urlgrey/dynamic-redis/
Github repo for Dockerfile: https://github.com/urlgrey/docker-dynamic-redis

Best,

--Scott Kidder

**Comment by mattsta** [comment]
Thanks!  Looks great.  Added a note about it to krmt at https://github.com/mattsta/krmt#about
